import {defineArrayMember, defineField, defineType} from 'sanity'

export const wholesalePage = defineType({
  name: 'wholesalePage',
  title: 'Wholesale Page',
  type: 'document',
  fields: [
    defineField({
      name: 'seoTitle',
      title: 'SEO title',
      type: 'string',
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO description',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.max(320),
    }),
    defineField({
      name: 'heroBadge',
      title: 'Hero badge',
      type: 'string',
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: 'heroHeading',
      title: 'Hero heading',
      type: 'string',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'heroSecondaryHeading',
      title: 'Hero secondary heading (H2)',
      type: 'string',
      description: 'Optional. Renders between the H1 and the intro paragraph (e.g. account registration).',
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: 'heroSubhead',
      title: 'Hero subhead',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroTrustLine1',
      title: 'Hero trust line 1',
      type: 'string',
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: 'heroTrustLine2',
      title: 'Hero trust line 2',
      type: 'string',
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: 'whyHeading',
      title: 'Why wholesale heading',
      type: 'string',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'whyIntro',
      title: 'Why wholesale intro',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'benefits',
      title: 'Why wholesale benefits',
      type: 'array',
      of: [
        defineArrayMember({type: 'wholesaleBenefit'}),
      ],
      validation: (rule) => rule.required().min(1).max(6),
    }),
    defineField({
      name: 'howHeading',
      title: 'How it works heading',
      type: 'string',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'howIntro',
      title: 'How it works intro',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'steps',
      title: 'How it works steps',
      type: 'array',
      of: [
        defineArrayMember({type: 'wholesaleStep'}),
      ],
      validation: (rule) => rule.required().min(1).max(6),
    }),
    defineField({
      name: 'discountHeading',
      title: 'Discount heading',
      type: 'string',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'discountIntro',
      title: 'Discount intro',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'paymentCardTitle',
      title: 'Payment card title',
      type: 'string',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'paymentCardDescription',
      title: 'Payment card description',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'cryptoRowLabel',
      title: 'Crypto row label',
      type: 'string',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'cryptoDiscountLabel',
      title: 'Crypto discount label',
      type: 'string',
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: 'revolutRowLabel',
      title: 'Revolut row label',
      type: 'string',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'revolutDiscountLabel',
      title: 'Revolut discount label',
      type: 'string',
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: 'volumeCardTitle',
      title: 'Volume card title',
      type: 'string',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'volumeCardDescription',
      title: 'Volume card description',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'volumeTiers',
      title: 'Volume tiers',
      type: 'array',
      of: [
        defineArrayMember({type: 'volumeTier'}),
      ],
      validation: (rule) => rule.required().min(1).max(6),
    }),
    defineField({
      name: 'discountSeeAlso',
      title: 'Discount note',
      type: 'string',
      description: 'Optional helper copy shown near the discount block.',
      validation: (rule) => rule.max(140),
    }),
    defineField({
      name: 'formHeading',
      title: 'Form heading',
      type: 'string',
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: 'formIntro',
      title: 'Form intro',
      type: 'string',
      validation: (rule) => rule.required().max(140),
    }),
    defineField({
      name: 'wholesaleRequestPage',
      title: 'Wholesale request page copy',
      type: 'object',
      fields: [
        defineField({name: 'badge', title: 'Badge', type: 'string', validation: (rule) => rule.required().max(80)}),
        defineField({name: 'heading', title: 'Heading', type: 'string', validation: (rule) => rule.required().max(120)}),
        defineField({name: 'intro', title: 'Intro', type: 'text', rows: 3, validation: (rule) => rule.required()}),
        defineField({name: 'thankYouHeading', title: 'Thank you heading', type: 'string', validation: (rule) => rule.required().max(120)}),
        defineField({name: 'thankYouIntro', title: 'Thank you intro', type: 'text', rows: 3, validation: (rule) => rule.required()}),
        defineField({name: 'thankYouNextStepsTitle', title: 'Next steps title', type: 'string', validation: (rule) => rule.required().max(100)}),
        defineField({name: 'thankYouUrgentHelpTitle', title: 'Urgent help title', type: 'string', validation: (rule) => rule.required().max(100)}),
        defineField({name: 'thankYouUrgentHelpBody', title: 'Urgent help body', type: 'text', rows: 3, validation: (rule) => rule.required()}),
        defineField({name: 'supportEmail', title: 'Support email', type: 'string', validation: (rule) => rule.required().email()}),
      ],
    }),
    defineField({
      name: 'testimonialsHeading',
      title: 'Testimonials heading',
      type: 'string',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'testimonialsIntro',
      title: 'Testimonials intro',
      type: 'string',
      validation: (rule) => rule.required().max(140),
    }),
    defineField({
      name: 'faqHeading',
      title: 'FAQ heading',
      type: 'string',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'faqIntro',
      title: 'FAQ intro',
      type: 'string',
      validation: (rule) => rule.required().max(140),
    }),
    defineField({
      name: 'faqs',
      title: 'FAQ items',
      type: 'array',
      of: [
        defineArrayMember({type: 'wholesaleFaq'}),
      ],
      validation: (rule) => rule.required().min(1).max(10),
    }),
  ],
  preview: {
    prepare: () => ({
      title: 'Wholesale Page',
      subtitle: 'Singleton wholesale page copy and section configuration',
    }),
  },
})